version: '3.1'

services:
  #アプリケーション側もDocker環境にコンバートする
  # bookmark_app_server:
  #   container_name: favorite_bookmark_app_sv
  #   build: './DockerFile/AppServer/'
  #   tty: true
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - api_server
  #   volumes:
  #     - ./share_favorite_book_mark/src:/share_favorite_book_mark/src

  api_server:
    container_name: favorite_bookmark_api_sv
    build: './DockerFile/ApiServer/'
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - ./server/api:/server/api
      - ./server/app:/server/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo_favorite_book_mark
    ports:
      - 27017:27017
    volumes:
      - ./server/db:/data/db
      - ./server/configdb:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_favorite_book_mark